#!/bin/bash

COLOR=\#FFFFFF

# openvpn
STATUS=$(systemctl is-active openvpn-client@*)

# expressvpn app
if [[ "$(expressvpn status)" =~ Connected.* ]]; then
	STATUS=active
fi

if [ -z "$STATUS" ]; then
	STATUS=inactive
fi
if [ $STATUS != "active" ]; then
	COLOR=\#FFAE00
fi

# openconnect
if [ -n "$(pidof openconnect)" ]; then
	if [ $STATUS == "active" ]; then
		# 2 vpns are running
		STATUS="MULTIPLE"
		COLOR=\#FFAE00
	else
		# this is a special case that I want to be
		# aware of. Make it green.
		STATUS="OPENCONNECT"
		COLOR=\#00FFAE
	fi
fi


echo $STATUS
echo $STATUS
echo $COLOR
